# Generated by Django 5.2.8 on 2026-02-09 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatix', '0004_alter_message_sender_alter_userinfo_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
